allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver
packages:
  - packages/*
  - extensions/*
  - externals/*
catalogs:
  common:
    '@changesets/cli': ^2.31.0
    '@types/node': ^25.9.3
    '@vscode/vsce': ^3.9.2
    defu: ^6.1.7
    naily-eslint-config: ^0.0.3
    pnpm: ^11.7.0
    typescript: ^6.0.2
    vite-plus: ^0.1.24
  vscode:
    '@volar/language-server': ^2.4.28
    '@volar/typescript': ^2.4.28
    '@volar/vscode': ^2.4.28
    volar-service-typescript: ^0.0.71
    vscode-uri: ^3.1.0
  webview:
    naive-ui: ^2.44.1
    vue: ^3.5.38
    vue-router: ^5.1.0
    vue-tsc: ^3.3.5
