/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Heading: typeof import('./../components/heading.vue')['default']
    LoadingSpinner: typeof import('./components/loading-spinner.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NCode: typeof import('naive-ui')['NCode']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NP: typeof import('naive-ui')['NP']
    NSelect: typeof import('naive-ui')['NSelect']
    NTab: typeof import('naive-ui')['NTab']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ProjectChoice: typeof import('./components/project-choice.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplateItem: typeof import('./components/template-item.vue')['default']
    TemplateTag: typeof import('./components/template-tag.vue')['default']
  }
}

// For TSX support
declare global {
  const Heading: typeof import('./../components/heading.vue')['default']
  const LoadingSpinner: typeof import('./components/loading-spinner.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NCarousel: typeof import('naive-ui')['NCarousel']
  const NCarouselItem: typeof import('naive-ui')['NCarouselItem']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
  const NCode: typeof import('naive-ui')['NCode']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NH1: typeof import('naive-ui')['NH1']
  const NH2: typeof import('naive-ui')['NH2']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NImage: typeof import('naive-ui')['NImage']
  const NInput: typeof import('naive-ui')['NInput']
  const NInputGroup: typeof import('naive-ui')['NInputGroup']
  const NP: typeof import('naive-ui')['NP']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NTab: typeof import('naive-ui')['NTab']
  const NTabPane: typeof import('naive-ui')['NTabPane']
  const NTabs: typeof import('naive-ui')['NTabs']
  const NTag: typeof import('naive-ui')['NTag']
  const NText: typeof import('naive-ui')['NText']
  const NTooltip: typeof import('naive-ui')['NTooltip']
  const ProjectChoice: typeof import('./components/project-choice.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TemplateItem: typeof import('./components/template-item.vue')['default']
  const TemplateTag: typeof import('./components/template-tag.vue')['default']
}