/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/device-manager/': RouteRecordInfo<
      '/device-manager/',
      '/device-manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/device-manager/create-device': RouteRecordInfo<
      '/device-manager/create-device',
      '/device-manager/create-device',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/device-manager/image-manager': RouteRecordInfo<
      '/device-manager/image-manager',
      '/device-manager/image-manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hdc-manager/': RouteRecordInfo<
      '/hdc-manager/',
      '/hdc-manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/': RouteRecordInfo<
      '/project/',
      '/project',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/template-detail': RouteRecordInfo<
      '/project/template-detail',
      '/project/template-detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/template-market': RouteRecordInfo<
      '/project/template-market',
      '/project/template-market',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/qualifier-editor/': RouteRecordInfo<
      '/qualifier-editor/',
      '/qualifier-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/frontend/pages/device-manager/index.vue': {
      routes:
        | '/device-manager/'
      views:
        | never
    }
    'src/frontend/pages/device-manager/create-device.vue': {
      routes:
        | '/device-manager/create-device'
      views:
        | never
    }
    'src/frontend/pages/device-manager/image-manager.vue': {
      routes:
        | '/device-manager/image-manager'
      views:
        | never
    }
    'src/frontend/pages/hdc-manager/index.vue': {
      routes:
        | '/hdc-manager/'
      views:
        | never
    }
    'src/frontend/pages/project/index.vue': {
      routes:
        | '/project/'
      views:
        | never
    }
    'src/frontend/pages/project/template-detail.vue': {
      routes:
        | '/project/template-detail'
      views:
        | never
    }
    'src/frontend/pages/project/template-market.vue': {
      routes:
        | '/project/template-market'
      views:
        | never
    }
    'src/frontend/pages/qualifier-editor/index.vue': {
      routes:
        | '/qualifier-editor/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
