name: PR CI

on:
  pull_request:
    branches:
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  lint:
    name: Run lint (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.17.0
          run_install: true

      - name: Run Lint
        run: pnpm run lint
  pack:
    name: Package Extension
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.17.0
          run_install: true

      - name: Package Extension (x64)
        run: pnpm -F vscode-naily-ets run pack --target ${{ matrix.os }}-x64
        env:
          OS: ${{ matrix.os }}
          ARCH: x64

      - name: Package Extension (arm64)
        run: pnpm -F vscode-naily-ets run pack --target ${{ matrix.os }}-arm64
        env:
          OS: ${{ matrix.os }}
          ARCH: arm64

      - name: Package Extension (armhf)
        run: pnpm -F vscode-naily-ets run pack --target ${{ matrix.os }}-armhf
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          OS: ${{ matrix.os }}
