name: PR CI

on:
  pull_request:
    branches:
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  lint:
    name: Run lint (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.17.0
          run_install: true

      - name: Run Lint
        run: pnpm run lint
  pack:
    name: Package Extension
    runs-on: ${{ matrix.settings.host }}
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        settings:
          - matrix:
              - host: macos-latest
                pack: pnpm run pack --target darwin-x64
                env:
                  OS: darwin
                  ARCH: x64
              - host: macos-latest
                pack: pnpm run pack --target darwin-arm64
                env:
                  OS: darwin
                  ARCH: arm64
              - host: ubuntu-latest
                pack: pnpm run pack --target linux-x64
                env:
                  OS: linux
                  ARCH: x64
              - host: ubuntu-latest
                pack: pnpm run pack --target linux-arm64
                env:
                  OS: linux
                  ARCH: arm64
              - host: ubuntu-latest
                pack: pnpm run pack --target alpine-x64
                env:
                  OS: linux
                  ARCH: x64
              - host: ubuntu-latest
                pack: pnpm run pack --target alpine-arm64
                env:
                  OS: linux
                  ARCH: armhf
              - host: ubuntu-latest
                pack: pnpm run pack --target linux-armhf
                env:
                  OS: linux
                  ARCH: arm64
              - host: windows-latest
                pack: pnpm run pack --target win32-x64
                env:
                  OS: win32
                  ARCH: x64
              - host: windows-latest
                pack: pnpm run pack --target win32-arm64
                env:
                  OS: win32
              - host: macos-latest
                pack: pnpm run pack --target web
                env:
                  OS: wasm32
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.17.0
          run_install: true

      - name: Run Pack
        run: pnpm run pack --target ${{ matrix.settings.pack }}
        env:
          OS: ${{ matrix.settings.env.OS }}
          ARCH: ${{ matrix.settings.env.ARCH }}
